// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CentralKitchen_Repositories.Models;

public partial class CentralKitchenDBContext : DbContext
{
    public CentralKitchenDBContext()
    {
    }

    public CentralKitchenDBContext(DbContextOptions<CentralKitchenDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Inventory> Inventories { get; set; }

    public virtual DbSet<InventoryTransaction> InventoryTransactions { get; set; }

    public virtual DbSet<Item> Items { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderLine> OrderLines { get; set; }

    public virtual DbSet<Production> Productions { get; set; }

    public virtual DbSet<QualityFeedback> QualityFeedbacks { get; set; }

    public virtual DbSet<Recipe> Recipes { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Shipment> Shipments { get; set; }

    public virtual DbSet<ShipmentLine> ShipmentLines { get; set; }

    public virtual DbSet<StockCheck> StockChecks { get; set; }

    public virtual DbSet<SystemParameter> SystemParameters { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<MaterialRequest> MaterialRequests { get; set; }

    public virtual DbSet<MaterialRequestLine> MaterialRequestLines { get; set; }

    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Inventory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__inventor__3213E83F66D05270");

            entity.ToTable("inventory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.LocationId).HasColumnName("location_id");
            entity.Property(e => e.Quantity)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("quantity");

            entity.HasOne(d => d.Item).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_inventory_item");

            entity.HasOne(d => d.Location).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_inventory_location");

            // thêm
            entity.Property(e => e.ManagedBy).HasColumnName("managed_by");

            entity.HasOne(d => d.ManagedByUser)
                .WithMany(p => p.ManagedInventories)
                .HasForeignKey(d => d.ManagedBy)
                .OnDelete(DeleteBehavior.ClientSetNull) // Hoặc SetNull tùy nhu cầu
                .HasConstraintName("fk_inventory_user");
        });

        modelBuilder.Entity<InventoryTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__inventor__3213E83F77EEC3AC");

            entity.ToTable("inventory_transactions");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.InventoryId).HasColumnName("inventory_id");
            entity.Property(e => e.Quantity)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("quantity");
            entity.Property(e => e.ReferenceId).HasColumnName("reference_id");
            entity.Property(e => e.ReferenceType)
                .HasMaxLength(30)
                .HasColumnName("reference_type");
            entity.Property(e => e.TxType)
                .HasMaxLength(30)
                .HasColumnName("tx_type");

            entity.HasOne(d => d.Inventory).WithMany(p => p.InventoryTransactions)
                .HasForeignKey(d => d.InventoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_inv_tx_inventory");
        });

        modelBuilder.Entity<Item>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__items__3213E83FD184E8CC");

            entity.ToTable("items");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("item_name");
            entity.Property(e => e.ItemType)
                .HasMaxLength(30)
                .HasColumnName("item_type");
            entity.Property(e => e.Unit)
                .HasMaxLength(20)
                .HasColumnName("unit");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("price");
            entity.Property(e => e.Category)
                .HasMaxLength(50)
                .HasColumnName("category");
            entity.Property(e => e.IsActive)
                .HasColumnName("is_active")
                .HasDefaultValue(true);
                });

        modelBuilder.Entity<Location>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__location__3213E83F14C50CBF");

            entity.ToTable("locations");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.LocationName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("location_name");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__orders__3213E83FAAD7D77A");

            entity.ToTable("orders");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("order_date");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasColumnName("status");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.ApprovedBy).HasColumnName("approved_by");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_orders_user");

            entity.HasOne(d => d.ApprovedByUser).WithMany()
                .HasForeignKey(d => d.ApprovedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_orders_approved_by");
        });

        modelBuilder.Entity<OrderLine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_li__3213E83FB535DE9E");

            entity.ToTable("order_lines");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Quantity)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("quantity");

            entity.HasOne(d => d.Item).WithMany(p => p.OrderLines)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_orderline_item");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderLines)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_orderline_order");
        });

        modelBuilder.Entity<Production>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__producti__3213E83F5D2D53C0");

            entity.ToTable("productions");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.LocationId).HasColumnName("location_id");
            entity.Property(e => e.ProductionDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("production_date");
            entity.Property(e => e.Quantity)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("quantity");

            entity.HasOne(d => d.Item).WithMany(p => p.Productions)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_production_item");

            entity.HasOne(d => d.Location).WithMany(p => p.Productions)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_production_location");
        });

        modelBuilder.Entity<QualityFeedback>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__quality___3213E83FA6343B80");

            entity.ToTable("quality_feedbacks");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.FeedbackDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("feedback_date");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Category)
                .HasMaxLength(30)
                .HasColumnName("category");
            entity.Property(e => e.Subject)
                .HasMaxLength(200)
                .HasColumnName("subject");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasDefaultValueSql("('Received')")
                .HasColumnName("status");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("fk_feedback_user");

            entity.HasOne(d => d.Order).WithMany()
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("fk_feedback_order");
        });

        modelBuilder.Entity<Recipe>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__recipes__3213E83FA1ACC16F");

            entity.ToTable("recipes");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FinishedItemId).HasColumnName("finished_item_id");
            entity.Property(e => e.IngredientItemId).HasColumnName("ingredient_item_id");
            entity.Property(e => e.Quantity)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("quantity");

            entity.HasOne(d => d.FinishedItem).WithMany(p => p.RecipeFinishedItems)
                .HasForeignKey(d => d.FinishedItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_recipe_finished_item");

            entity.HasOne(d => d.IngredientItem).WithMany(p => p.RecipeIngredientItems)
                .HasForeignKey(d => d.IngredientItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_recipe_ingredient_item");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__roles__3213E83F5CBCC5E7");

            entity.ToTable("roles");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("role_name");
        });

        modelBuilder.Entity<Shipment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__shipment__3213E83FA227DCFA");

            entity.ToTable("shipments");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FromLocationId).HasColumnName("from_location_id");
            entity.Property(e => e.ShipmentDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("shipment_date");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasColumnName("status");

            entity.HasOne(d => d.FromLocation).WithMany(p => p.Shipments)
                .HasForeignKey(d => d.FromLocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_shipment_location");
        });

        modelBuilder.Entity<ShipmentLine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__shipment__3213E83FEE1E3CB0");

            entity.ToTable("shipment_lines");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.Quantity)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("quantity");
            entity.Property(e => e.ShipmentId).HasColumnName("shipment_id");

            entity.HasOne(d => d.Item).WithMany(p => p.ShipmentLines)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_shipmentline_item");

            entity.HasOne(d => d.Shipment).WithMany(p => p.ShipmentLines)
                .HasForeignKey(d => d.ShipmentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_shipmentline_shipment");
        });

        modelBuilder.Entity<StockCheck>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__stock_ch__3213E83FE3C0E1F5");

            entity.ToTable("stock_checks");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CheckDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("check_date");
            entity.Property(e => e.LocationId).HasColumnName("location_id");
            entity.Property(e => e.Note)
                .HasMaxLength(255)
                .HasColumnName("note");

            entity.HasOne(d => d.Location).WithMany(p => p.StockChecks)
                .HasForeignKey(d => d.LocationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_stockcheck_location");
        });

        modelBuilder.Entity<SystemParameter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__system_p__3213E83FFD6792C9");

            entity.ToTable("system_parameters");

            entity.HasIndex(e => e.ParamKey, "UQ__system_p__18BAEC9F2EAA2875").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ParamKey)
                .HasMaxLength(50)
                .HasColumnName("param_key");
            entity.Property(e => e.ParamValue)
                .HasMaxLength(255)
                .HasColumnName("param_value");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83F04B34198");

            entity.ToTable("users");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.RoleId).HasColumnName("role_id");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("username");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_users_roles");
        });

        modelBuilder.Entity<MaterialRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_material_requests");

            entity.ToTable("material_requests");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.RequestedByUserId).HasColumnName("requested_by_user_id");
            entity.Property(e => e.Status)
                .HasMaxLength(30)
                .HasColumnName("status");
            entity.Property(e => e.Note)
                .HasMaxLength(500)
                .HasColumnName("note");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("created_at");
                
            entity.Property(e => e.AcceptedBy).HasColumnName("accepted_by");

            entity.HasOne(d => d.Order).WithMany(p => p.MaterialRequests)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_material_request_order");

            entity.HasOne(d => d.RequestedByUser).WithMany(p => p.MaterialRequests)
                .HasForeignKey(d => d.RequestedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_material_request_user");
                
            entity.HasOne(d => d.AcceptedByUser).WithMany(p => p.AcceptedMaterialRequests)
                .HasForeignKey(d => d.AcceptedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_material_request_accepted_by");
        });

        modelBuilder.Entity<MaterialRequestLine>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_material_request_lines");

            entity.ToTable("material_request_lines");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.MaterialRequestId).HasColumnName("material_request_id");
            entity.Property(e => e.ItemId).HasColumnName("item_id");
            entity.Property(e => e.RequestedQuantity)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("requested_quantity");
            entity.Property(e => e.CurrentStock)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("current_stock");

            entity.HasOne(d => d.MaterialRequest).WithMany(p => p.MaterialRequestLines)
                .HasForeignKey(d => d.MaterialRequestId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_mrl_material_request");

            entity.HasOne(d => d.Item).WithMany(p => p.MaterialRequestLines)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_mrl_item");
        });

        modelBuilder.Entity<QualityFeedback>(entity =>
        {
            entity.ToTable("quality_feedbacks");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.OrderId).HasColumnName("order_id");
            entity.Property(e => e.Category).HasMaxLength(50).HasColumnName("category");
            entity.Property(e => e.Subject).HasMaxLength(200).HasColumnName("subject");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Status).HasMaxLength(30).HasColumnName("status");
            entity.Property(e => e.FeedbackDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("feedback_date");
            entity.Property(e => e.Rating).HasColumnName("rating");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_feedback_user");

            entity.HasOne(d => d.Order).WithMany()
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_feedback_order");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}