// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class InventoryTransaction
{
    public int Id { get; set; }

    public int InventoryId { get; set; }

    public string TxType { get; set; }

    public decimal? Quantity { get; set; }

    public string ReferenceType { get; set; }

    public int? ReferenceId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Inventory Inventory { get; set; }
}