// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class Inventory
{
    public int Id { get; set; }

    public int ItemId { get; set; }

    public int LocationId { get; set; }

    public decimal? Quantity { get; set; }

    public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new List<InventoryTransaction>();

    public virtual Item Item { get; set; }

    public virtual Location Location { get; set; }
    //thêm 
    public int? ManagedBy { get; set; } // Cột managed_by

    public virtual User ManagedByUser { get; set; } // Navigation property
}