// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class Item
{
    public int Id { get; set; }

    public string ItemName { get; set; }

    public string Unit { get; set; }

    public string ItemType { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    public virtual ICollection<Production> Productions { get; set; } = new List<Production>();

    public virtual ICollection<QualityFeedback> QualityFeedbacks { get; set; } = new List<QualityFeedback>();

    public virtual ICollection<Recipe> RecipeFinishedItems { get; set; } = new List<Recipe>();

    public virtual ICollection<Recipe> RecipeIngredientItems { get; set; } = new List<Recipe>();

    public virtual ICollection<ShipmentLine> ShipmentLines { get; set; } = new List<ShipmentLine>();
}