// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class QualityFeedback
{
    public int Id { get; set; }

    public int? ItemId { get; set; }

    public string Description { get; set; }

    public DateTime? FeedbackDate { get; set; }

    public virtual Item Item { get; set; }
}