// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class Recipe
{
    public int Id { get; set; }

    public int FinishedItemId { get; set; }

    public int IngredientItemId { get; set; }

    public decimal Quantity { get; set; }

    public virtual Item FinishedItem { get; set; }

    public virtual Item IngredientItem { get; set; }
}