// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class ShipmentLine
{
    public int Id { get; set; }

    public int ShipmentId { get; set; }

    public int ItemId { get; set; }

    public decimal? Quantity { get; set; }

    public virtual Item Item { get; set; }

    public virtual Shipment Shipment { get; set; }
}