// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class Shipment
{
    public int Id { get; set; }

    public int FromLocationId { get; set; }

    public DateTime? ShipmentDate { get; set; }

    public string Status { get; set; }

    public virtual Location FromLocation { get; set; }

    public virtual ICollection<ShipmentLine> ShipmentLines { get; set; } = new List<ShipmentLine>();
}