// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class StockCheck
{
    public int Id { get; set; }

    public int LocationId { get; set; }

    public DateTime? CheckDate { get; set; }

    public string Note { get; set; }

    public virtual Location Location { get; set; }
}