// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CentralKitchen_Repositories.Models;

public partial class SystemParameter
{
    public int Id { get; set; }

    public string ParamKey { get; set; }

    public string ParamValue { get; set; }
}