// <auto-generated />
using System;
using CentralKitchen_Repositories.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralKitchen_Repositories.Migrations
{
    [DbContext(typeof(CentralKitchenDBContext))]
    partial class CentralKitchenDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<int?>("ManagedBy")
                        .HasColumnType("int")
                        .HasColumnName("managed_by");

                    b.Property<decimal?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__inventor__3213E83F66D05270");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ManagedBy");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("quantity");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("reference_type");

                    b.Property<string>("TxType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tx_type");

                    b.HasKey("Id")
                        .HasName("PK__inventor__3213E83F77EEC3AC");

                    b.HasIndex("InventoryId");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("item_type");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("PK__items__3213E83FD184E8CC");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location_name");

                    b.HasKey("Id")
                        .HasName("PK__location__3213E83F14C50CBF");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.MaterialRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK_material_requests");

                    b.HasIndex("OrderId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("material_requests", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.MaterialRequestLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CurrentStock")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("current_stock");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("int")
                        .HasColumnName("material_request_id");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("requested_quantity");

                    b.HasKey("Id")
                        .HasName("PK_material_request_lines");

                    b.HasIndex("ItemId");

                    b.HasIndex("MaterialRequestId");

                    b.ToTable("material_request_lines", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__orders__3213E83FAAD7D77A");

                    b.HasIndex("UserId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__order_li__3213E83FB535DE9E");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_lines", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<DateTime?>("ProductionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("production_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__producti__3213E83F5D2D53C0");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.ToTable("productions", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.QualityFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("FeedbackDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("feedback_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.HasKey("Id")
                        .HasName("PK__quality___3213E83FA6343B80");

                    b.HasIndex("ItemId");

                    b.ToTable("quality_feedbacks", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FinishedItemId")
                        .HasColumnType("int")
                        .HasColumnName("finished_item_id");

                    b.Property<int>("IngredientItemId")
                        .HasColumnType("int")
                        .HasColumnName("ingredient_item_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__recipes__3213E83FA1ACC16F");

                    b.HasIndex("FinishedItemId");

                    b.HasIndex("IngredientItemId");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("Id")
                        .HasName("PK__roles__3213E83F5CBCC5E7");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromLocationId")
                        .HasColumnType("int")
                        .HasColumnName("from_location_id");

                    b.Property<DateTime?>("ShipmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("shipment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__shipment__3213E83FA227DCFA");

                    b.HasIndex("FromLocationId");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("quantity");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id")
                        .HasName("PK__shipment__3213E83FEE1E3CB0");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("shipment_lines", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.StockCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("check_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("PK__stock_ch__3213E83FE3C0E1F5");

                    b.HasIndex("LocationId");

                    b.ToTable("stock_checks", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.SystemParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ParamKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("param_key");

                    b.Property<string>("ParamValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("param_value");

                    b.HasKey("Id")
                        .HasName("PK__system_p__3213E83FFD6792C9");

                    b.HasIndex(new[] { "ParamKey" }, "UQ__system_p__18BAEC9F2EAA2875")
                        .IsUnique()
                        .HasFilter("[param_key] IS NOT NULL");

                    b.ToTable("system_parameters", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F04B34198");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Inventory", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("fk_inventory_item");

                    b.HasOne("CentralKitchen_Repositories.Models.Location", "Location")
                        .WithMany("Inventories")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("fk_inventory_location");

                    b.HasOne("CentralKitchen_Repositories.Models.User", "ManagedByUser")
                        .WithMany("ManagedInventories")
                        .HasForeignKey("ManagedBy")
                        .HasConstraintName("fk_inventory_user");

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("ManagedByUser");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.InventoryTransaction", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Inventory", "Inventory")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("InventoryId")
                        .IsRequired()
                        .HasConstraintName("fk_inv_tx_inventory");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.MaterialRequest", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Order", "Order")
                        .WithMany("MaterialRequests")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_material_request_order");

                    b.HasOne("CentralKitchen_Repositories.Models.User", "RequestedByUser")
                        .WithMany("MaterialRequests")
                        .HasForeignKey("RequestedByUserId")
                        .IsRequired()
                        .HasConstraintName("fk_material_request_user");

                    b.Navigation("Order");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.MaterialRequestLine", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Item", "Item")
                        .WithMany("MaterialRequestLines")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("fk_mrl_item");

                    b.HasOne("CentralKitchen_Repositories.Models.MaterialRequest", "MaterialRequest")
                        .WithMany("MaterialRequestLines")
                        .HasForeignKey("MaterialRequestId")
                        .IsRequired()
                        .HasConstraintName("fk_mrl_material_request");

                    b.Navigation("Item");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Order", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_orders_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.OrderLine", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Item", "Item")
                        .WithMany("OrderLines")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("fk_orderline_item");

                    b.HasOne("CentralKitchen_Repositories.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_orderline_order");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Production", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Item", "Item")
                        .WithMany("Productions")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("fk_production_item");

                    b.HasOne("CentralKitchen_Repositories.Models.Location", "Location")
                        .WithMany("Productions")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("fk_production_location");

                    b.Navigation("Item");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.QualityFeedback", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Item", "Item")
                        .WithMany("QualityFeedbacks")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("fk_feedback_item");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Recipe", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Item", "FinishedItem")
                        .WithMany("RecipeFinishedItems")
                        .HasForeignKey("FinishedItemId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_finished_item");

                    b.HasOne("CentralKitchen_Repositories.Models.Item", "IngredientItem")
                        .WithMany("RecipeIngredientItems")
                        .HasForeignKey("IngredientItemId")
                        .IsRequired()
                        .HasConstraintName("fk_recipe_ingredient_item");

                    b.Navigation("FinishedItem");

                    b.Navigation("IngredientItem");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Shipment", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Location", "FromLocation")
                        .WithMany("Shipments")
                        .HasForeignKey("FromLocationId")
                        .IsRequired()
                        .HasConstraintName("fk_shipment_location");

                    b.Navigation("FromLocation");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.ShipmentLine", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Item", "Item")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("fk_shipmentline_item");

                    b.HasOne("CentralKitchen_Repositories.Models.Shipment", "Shipment")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("ShipmentId")
                        .IsRequired()
                        .HasConstraintName("fk_shipmentline_shipment");

                    b.Navigation("Item");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.StockCheck", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Location", "Location")
                        .WithMany("StockChecks")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("fk_stockcheck_location");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.User", b =>
                {
                    b.HasOne("CentralKitchen_Repositories.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_users_roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Inventory", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Item", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("MaterialRequestLines");

                    b.Navigation("OrderLines");

                    b.Navigation("Productions");

                    b.Navigation("QualityFeedbacks");

                    b.Navigation("RecipeFinishedItems");

                    b.Navigation("RecipeIngredientItems");

                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Location", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("Productions");

                    b.Navigation("Shipments");

                    b.Navigation("StockChecks");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.MaterialRequest", b =>
                {
                    b.Navigation("MaterialRequestLines");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Order", b =>
                {
                    b.Navigation("MaterialRequests");

                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("CentralKitchen_Repositories.Models.User", b =>
                {
                    b.Navigation("ManagedInventories");

                    b.Navigation("MaterialRequests");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
